#!/bin/bash

gmx grompp -f EM_chain.mdp -o EM_chain.tpr -c chain_org2.pdb -p chain.top -n chain.ndx -maxwarn 4
srun gmx_mpi mdrun -s EM_chain.tpr -o EM_chain.trr -c EM_chain.pdb -g EM_chain.log -e EM_chain.edr -v -tableb table_{a1,a2,a12,a22,a10,a3,a11,a32,a3,d10,d11,d12,d13,d21,d22,d23,d31,d32,d33}.xvg -maxh 0.5

gmx grompp -f EQ_chain.mdp -o EQ_chain.tpr -c EM_chain.pdb -p chain.top -n chain.ndx -maxwarn 4
srun gmx_mpi mdrun -s EQ_chain.tpr -o EQ_chain.trr -c EQ_chain.pdb -g EQ_chain.log -e EQ_chain.edr -v -tableb table_{a1,a2,a12,a22,a10,a3,a11,a32,a3,d10,d11,d12,d13,d21,d22,d23,d31,d32,d33}.xvg

gmx grompp -f MD_chain.mdp -o MD_chain.tpr -c EQ_chain.pdb -p chain.top -n chain.ndx -maxwarn 4
srun gmx_mpi mdrun -s MD_chain.tpr -o MD_chain.trr -c MD_chain.pdb -g MD_chain.log -e MD_chain.edr -v -tableb table_{a1,a2,a12,a22,a10,a3,a11,a32,a3,d10,d11,d12,d13,d21,d22,d23,d31,d32,d33}.xvg

#prepare for hydro runs
cp ./hydro/*.exe .
chmod +x *.exe

echo 0 | gmx trjconv -f MD_chain.trr -s MD_chain.tpr -pbc nojump -o hydro.xtc

echo 0 | gmx traj -s MD_chain.tpr -n chain.ndx -f hydro.xtc -oxt MD_chain_hydro.pdb -b 500000

rm hydro.xtc
chmod +x ./runhydro.py

./runhydro.py
